### ISSUE TITLE
Cannot compile ts file when importing .clist module

### ISSUE THREAD

**Issue by justinmann** [mezum/emcc-loader#2]
I am having trouble using your loader with typescript. I assume the problem is in the module resolution for tsc, which I have currently set to "node". 

Here is a sample app:
https://github.com/justinmann/aws-demo

Here is the error:
[tsl] ERROR in /Users/jusmann/aws/aws-demo/src/app.ts(2,18)
      TS2307: Cannot find module './foo.clist'.

**Comment by mezum** [comment]
Sorry for the late reply
and thank you for using my loader and reporting this issue.

This loader should generate a .d.ts file for a .clist file, but not yet.
Currently, I calmed TypeScript down with a .d.ts written on my hand like this:

```typescript
// ./foo.clist.d.ts
export interface Assembly {
    _sayHello() : void;
    // ... add declarations of exported function here.
}

// following lines is template code.

export interface Module {
   asm : Assembly;
}

export interface ModuleLoader {
    initialize(userModule : any) : Promise<Module>;
}

declare const loader : ModuleLoader;
export default loader;
```

By the way, I think this issue is duplicate with #1.
So may I close this issue?

**Comment by justinmann** [comment]
That fixed it. I have pushed my changes.
